# Generated by Django 5.1.1 on 2024-09-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', '-updated']},
        ),
    ]
