# Generated by Django 5.1.1 on 2024-10-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVarificationEvent',
            new_name='EmailVerificationEvent',
        ),
    ]
